// This file was automatically generated by the Dapper.SimpleCRUD T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `MainConnectionString`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `server=.;uid=sa;pwd=t1h9a8n9h;database=QLCC_Db;connection timeout=50`
//     Include Views:          `True`

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace QLCCVC.DAL.Models
{

}
